### ISSUE TITLE
Error when running packet2audio

### ISSUE THREAD

**Issue by 3vangel1st** [phillipdavidstearns/packet2audio#1]
I've tried to install packet2radio both on Debian v8 and v10 but getting the same error - is this a script error or something else? I'd love to test your script in my research.

command: packet2audio.py -i etho

error: 
File "packet2audio.py" , line 82
print ("INTERFACES: " , end= ' '_
                                               ^

**Comment by brannondorsey** [comment]
It looks like you are running `packet2audio.py` with Python2 instead of Python3. Make sure you have Python3 installed (via the instructions in the README). 

The `#!/usr/bin/env python3` shebang at the top of `packet2audio.py` should coerce your shell into evaluating the script with Python3 on its own, but if that doesn't appear to be working, try running the script like this instead:

```bash
python3 packet2audio.py -i eth0
```
